stages:
  - mirror

mirror:
  stage: mirror
  before_script:
    - git config --global user.email "caruso@ocelot.ltd"
    - git config --global user.name "SolCaruso"
  script:
    - git clone --mirror "$CI_REPOSITORY_URL" repo-mirror
    - cd repo-mirror
    - git remote add github "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/SolCaruso/vercel.git"
    - git push --mirror github
  only:
    - dev